version: '2'
services:
  cdr:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=beebon
    ports:
      - "3306:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/beebon/mysql/lib/mysql:/var/lib/mysql"
    restart: always

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
#      - "./config/etc/redis/:/usr/local/etc/redis/"
      - "/var/store/beebon/redis/:/data"
    restart: always

#  beebon-collector:
#    build: ./
#    ports:
#      - "3030:3030"
    # environment:
    #   - NODE_ENV=default
    #   - NODE_CONFIG_DIR=/etc/beebon
    # volumes:
    #   - "/etc/localtime:/etc/localtime:ro"
    #   - "./config/:/etc/beebon"
    # restart: always