version: '2'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=beebon
    ports:
      - "3306:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/beebon/mysql/lib/mysql:/var/lib/mysql"
    restart: always

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/store/beebon/redis/:/data"
    restart: always

  collector:
    image: antirek/beebon
    command: node collector
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=default
      - NODE_CONFIG_DIR=/etc/beebon
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/:/etc/beebon"
    restart: always

  web:
    image: antirek/beebon
    command: node web
    ports:
      - "3101:3101"
    environment:
      - NODE_ENV=default
      - NODE_CONFIG_DIR=/etc/beebon
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/:/etc/beebon"
    restart: always

  reporter:
    image: antirek/beebon
    command: node reporter
    environment:
      - NODE_ENV=default
      - NODE_CONFIG_DIR=/etc/beebon
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/:/etc/beebon"
    restart: always